Repository SinhanDS-Project/pongdang-back, pull requests merged in 2025-09, with the labels that each got.

#30 ✨ [feat] Betting Point DB 연동
  build.gradle
  src/main/java/com/wepong/pongdang/config/MariaDBConfig.java
  src/main/java/com/wepong/pongdang/config/MySQLConfig.java
  src/main/java/com/wepong/pongdang/entity/UserEntity.java
  src/main/java/net/wepong/mysql/entity/UserEntity.java
  src/main/java/net/wepong/mysql/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 🐛 bug, ✨ feature, 🚀 chore

#42 ✨ [feat] 출석체크 기능 구현
  src/main/java/com/wepong/pongdang/controller/AttendanceRestController.java
  src/main/java/com/wepong/pongdang/controller/GlobalExceptionHandler.java
  src/main/java/com/wepong/pongdang/dto/response/AttendanceResponseDTO.java
  src/main/java/com/wepong/pongdang/entity/AttendanceEntity.java
  src/main/java/com/wepong/pongdang/exception/AlreadyAttendanceException.java
  src/main/java/com/wepong/pongdang/exception/ExceptionMessage.java
  src/main/java/com/wepong/pongdang/exception/UserCannotFoundException.java
  src/main/java/com/wepong/pongdang/repository/AttendanceRepository.java
  src/main/java/com/wepong/pongdang/service/AttendanceService.java
  src/main/java/com/wepong/pongdang/service/QuizCheckService.java
Labels: ✨ feature

#45 🚀 [chore] 기부 및 상품 예외 처리
  src/main/java/com/wepong/pongdang/controller/DonationController.java
  src/main/java/com/wepong/pongdang/controller/GameRoomRestController.java
  src/main/java/com/wepong/pongdang/controller/GlobalExceptionHandler.java
  src/main/java/com/wepong/pongdang/controller/StoreController.java
  src/main/java/com/wepong/pongdang/exception/DonationNotFoundException.java
  src/main/java/com/wepong/pongdang/exception/ExceptionMessage.java
  src/main/java/com/wepong/pongdang/exception/ProductNotFoundException.java
  src/main/java/com/wepong/pongdang/service/DonationService.java
  src/main/java/com/wepong/pongdang/service/StoreService.java
Labels: 🐛 bug, 🚀 chore

#50 🚀 [chore] 출석체크 로직 변경
  src/main/java/com/wepong/pongdang/dto/response/AttendanceResponseDTO.java
  src/main/java/com/wepong/pongdang/repository/AttendanceRepository.java
  src/main/java/com/wepong/pongdang/service/AttendanceService.java
Labels: ✨ feature, 🚀 chore

#51 ✨ [feat] 전체 실시간 알림 기능 구현
  src/main/java/com/wepong/pongdang/config/WebConfig.java
  src/main/java/com/wepong/pongdang/controller/GameRoomController.java
  src/main/java/com/wepong/pongdang/controller/GameRoomRestController.java
  src/main/java/com/wepong/pongdang/controller/TurtleGameController.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameService.java
  src/main/java/com/wepong/pongdang/service/DonationService.java
  src/main/java/com/wepong/pongdang/service/GameRoomService.java
  src/main/java/com/wepong/pongdang/service/QuizCheckService.java
  src/main/java/com/wepong/pongdang/service/WebSocketService.java
  src/main/java/com/wepong/pongdang/socket/StompAuthChannelInterceptor.java
  src/main/java/com/wepong/pongdang/socket/StompEventListener.java
  src/main/java/com/wepong/pongdang/socket/WebSocketConfig.java
Labels: 🐛 bug, 💻 edit, ✨ feature

#55 🐛 [fix] 문의 내역 오류 수정
  src/main/java/com/wepong/pongdang/controller/ChatLogRestController.java
  src/main/java/com/wepong/pongdang/service/ChatLogService.java
Labels: 🐛 bug

#58 ♻️ [refactor] 게시판 댓글 수정
  src/main/java/com/wepong/pongdang/controller/ReplyRestController.java
  src/main/java/com/wepong/pongdang/entity/ChatLogsEntity.java
Labels: ♻️ refactor

#63 ♻️ [refactor] 거북이 게임 로직 수정
  src/main/java/com/wepong/pongdang/controller/GameRoomController.java
  src/main/java/com/wepong/pongdang/controller/GameRoomRestController.java
  src/main/java/com/wepong/pongdang/dto/response/GameRoomResponseDTO.java
  src/main/java/com/wepong/pongdang/entity/enums/PongHistoryType.java
  src/main/java/com/wepong/pongdang/filter/JwtAuthenticationFilter.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/PlayerService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/SessionService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameState.java
  src/main/java/com/wepong/pongdang/service/GameRoomService.java
  src/main/java/com/wepong/pongdang/socket/GameRoomListWebSocket.java
  src/main/java/com/wepong/pongdang/socket/GameRoomWebSocketHandler.java
  src/main/java/com/wepong/pongdang/socket/RawWebSocketConfig.java
  src/main/java/com/wepong/pongdang/socket/RoomListHandshakeInterceptor.java
  src/main/java/com/wepong/pongdang/socket/StompAuthChannelInterceptor.java
  src/main/java/com/wepong/pongdang/socket/TurtleHandshakeInterceptor.java
  src/main/java/com/wepong/pongdang/socket/TurtleRunWebsocketHandler.java
  src/main/java/com/wepong/pongdang/socket/WebSocketConfig.java
Labels: 🐛 bug, 💻 edit, ✨ feature, ♻️ refactor

#66 ♻️ [refactor] 전환하기 오류 수정
  src/main/java/net/wepong/mysql/service/BettingUserPointService.java
Labels: ♻️ refactor

#67 🚀 [chore] 클라이언트 응답 바디 생성 및 예외 처리
  src/main/java/com/wepong/pongdang/config/WebConfig.java
  src/main/java/com/wepong/pongdang/controller/AdminController.java
  src/main/java/com/wepong/pongdang/controller/AuthRestController.java
  src/main/java/com/wepong/pongdang/controller/BoardRestController.java
  src/main/java/com/wepong/pongdang/controller/GameRestController.java
  src/main/java/com/wepong/pongdang/controller/GameRoomController.java
  src/main/java/com/wepong/pongdang/controller/GameRoomRestController.java
  src/main/java/com/wepong/pongdang/controller/GlobalExceptionHandler.java
  src/main/java/com/wepong/pongdang/controller/HistoryRestController.java
  src/main/java/com/wepong/pongdang/controller/PhoneVerificationRestController.java
  src/main/java/com/wepong/pongdang/controller/ReplyRestController.java
  src/main/java/com/wepong/pongdang/controller/TurtleGameController.java
  src/main/java/com/wepong/pongdang/controller/UserRestController.java
  src/main/java/com/wepong/pongdang/controller/VerificationRestController.java
  src/main/java/com/wepong/pongdang/exception/EmailAlreadyExistsException.java
  src/main/java/com/wepong/pongdang/exception/ExceptionMessage.java
  src/main/java/com/wepong/pongdang/exception/InvalidBirthDateException.java
  src/main/java/com/wepong/pongdang/exception/InvalidPasswordFormatException.java
  src/main/java/com/wepong/pongdang/exception/InvalidPhoneNumberFormatException.java
  src/main/java/com/wepong/pongdang/exception/MissingRequiredFieldsException.java
  src/main/java/com/wepong/pongdang/exception/NicknameAlreadyExist.java
  src/main/java/com/wepong/pongdang/exception/PasswordMismatchException.java
  src/main/java/com/wepong/pongdang/exception/PrivacyAgreementRequiredException.java
  src/main/java/com/wepong/pongdang/exception/RefreshTokenNotFoundException.java
  src/main/java/com/wepong/pongdang/exception/UnderAgeException.java
  src/main/java/com/wepong/pongdang/exception/UserAlreadyLinkedException.java
  src/main/java/com/wepong/pongdang/exception/UserAlreadyRegisteredException.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameService.java
  src/main/java/com/wepong/pongdang/service/AdminService.java
  src/main/java/com/wepong/pongdang/service/AuthService.java
  src/main/java/com/wepong/pongdang/service/DonationService.java
  src/main/java/com/wepong/pongdang/service/GameRoomService.java
  src/main/java/com/wepong/pongdang/service/HistoryService.java
  src/main/java/com/wepong/pongdang/service/VerificationService.java
  src/main/java/com/wepong/pongdang/service/WebSocketService.java
  src/main/java/com/wepong/pongdang/socket/StompAuthChannelInterceptor.java
  src/main/java/com/wepong/pongdang/socket/StompEventListener.java
Labels: 🚀 chore, ⚡️ perf

#72 ✨ [feat] 인증번호 이메일 템플릿 추가
  src/main/java/com/wepong/pongdang/controller/VerificationRestController.java
  src/main/java/com/wepong/pongdang/model/email/ProductTemplate.java
  src/main/java/com/wepong/pongdang/model/email/TempPasswordTemplate.java
  src/main/java/com/wepong/pongdang/model/email/VerificationTemplate.java
  src/main/java/com/wepong/pongdang/service/BarcodeService.java
  src/main/java/com/wepong/pongdang/service/VerificationService.java
Labels: 🐛 bug, 💻 edit, ✨ feature

#81 [feat] 구매내역, 기부내역, 응답데이터 CreateAt추가
  src/main/java/com/wepong/pongdang/dto/response/DonationResponseDTO.java
  src/main/java/com/wepong/pongdang/dto/response/PurchaseResponseDTO.java
Labels: ✨ feature

#77 ✨ [feat] 보드게임 웹소켓 구현 및 이벤트 처리
  src/main/java/com/wepong/pongdang/controller/BoardGameController.java
  src/main/java/com/wepong/pongdang/controller/GameRestController.java
  src/main/java/com/wepong/pongdang/controller/GameRoomController.java
  src/main/java/com/wepong/pongdang/controller/GameRoomRestController.java
  src/main/java/com/wepong/pongdang/controller/GlobalExceptionHandler.java
  src/main/java/com/wepong/pongdang/controller/PlayerRestController.java
  src/main/java/com/wepong/pongdang/controller/TurtleGameController.java
  src/main/java/com/wepong/pongdang/controller/WalletController.java
  src/main/java/com/wepong/pongdang/dto/request/GameRoomRequestDTO.java
  src/main/java/com/wepong/pongdang/dto/request/WalletRequestDTO.java
  src/main/java/com/wepong/pongdang/dto/response/ChatResponseDTO.java
  src/main/java/com/wepong/pongdang/dto/response/GameLevelResponseDTO.java
  src/main/java/com/wepong/pongdang/dto/response/GameRoomResponseDTO.java
  src/main/java/com/wepong/pongdang/entity/AttendanceEntity.java
  src/main/java/com/wepong/pongdang/entity/enums/EventType.java
  src/main/java/com/wepong/pongdang/entity/enums/PongHistoryType.java
  src/main/java/com/wepong/pongdang/exception/AlreadyBubbleException.java
  src/main/java/com/wepong/pongdang/exception/AlreadyTransferException.java
  src/main/java/com/wepong/pongdang/exception/ExceptionMessage.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardGameService.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardPlayerDAO.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardPlayerDTO.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardPlayerService.java
  src/main/java/com/wepong/pongdang/model/multi/board/LandDAO.java
  src/main/java/com/wepong/pongdang/model/multi/board/LandDTO.java
  src/main/java/com/wepong/pongdang/model/multi/board/LandService.java
  src/main/java/com/wepong/pongdang/model/multi/board/RoomStateDAO.java
  src/main/java/com/wepong/pongdang/model/multi/board/RoomStateDTO.java
  src/main/java/com/wepong/pongdang/model/multi/board/RoomStateService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/PlayerService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameState.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtlePlayerDAO.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtlePlayerDTO.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtlePlayerService.java
  src/main/java/com/wepong/pongdang/repository/AttendanceRepository.java
  src/main/java/com/wepong/pongdang/service/AttendanceService.java
  src/main/java/com/wepong/pongdang/service/GameRoomService.java
  src/main/java/com/wepong/pongdang/service/QuizService.java
  src/main/java/com/wepong/pongdang/service/WebSocketService.java
  src/main/java/com/wepong/pongdang/socket/StompAuthChannelInterceptor.java
  src/main/java/com/wepong/pongdang/socket/StompEventListener.java
Labels: 🐛 bug, 💻 edit, ✨ feature, 🚀 chore

#84 ✨ [feat] 개인 이벤트 수정
  src/main/java/com/wepong/pongdang/controller/AttendanceRestController.java
  src/main/java/com/wepong/pongdang/controller/GameRestController.java
  src/main/java/com/wepong/pongdang/controller/PaymentRestController.java
  src/main/java/com/wepong/pongdang/controller/WalletController.java
  src/main/java/com/wepong/pongdang/entity/enums/EventType.java
  src/main/java/com/wepong/pongdang/entity/enums/PointHistoryType.java
  src/main/java/com/wepong/pongdang/entity/enums/PongHistoryType.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardGameService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameService.java
  src/main/java/com/wepong/pongdang/service/AttendanceService.java
  src/main/java/com/wepong/pongdang/service/DonationService.java
  src/main/java/com/wepong/pongdang/service/HistoryService.java
  src/main/java/com/wepong/pongdang/service/PointConvertService.java
  src/main/java/com/wepong/pongdang/service/QuizCheckService.java
  src/main/java/com/wepong/pongdang/service/StoreService.java
  src/main/java/com/wepong/pongdang/service/WalletService.java
Labels: 🐛 bug, 💻 edit

#86 ✨ [feat] 서버 배포 준비
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/resources/application.yml
Labels: 💚 ci, 🚀 chore

#89 ✨ [feat] 보드게임 웹소켓 수정/추가
  src/main/java/com/wepong/pongdang/controller/BoardGameController.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardGameService.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardPlayerDTO.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardPlayerService.java
  src/main/java/com/wepong/pongdang/service/WebSocketService.java
  src/main/java/com/wepong/pongdang/socket/StompEventListener.java
Labels: 💻 edit, ✨ feature

#93 ✨🐛 [feat] 배포 후 기능 추가 및 서버 오류 수정
  src/main/java/com/wepong/pongdang/controller/AuthRestController.java
  src/main/java/com/wepong/pongdang/entity/enums/PongHistoryType.java
  src/main/java/com/wepong/pongdang/model/multi/board/LandService.java
  src/main/java/com/wepong/pongdang/service/ChatLogService.java
  src/main/java/com/wepong/pongdang/service/HistoryService.java
  src/main/java/com/wepong/pongdang/service/PointConvertService.java
  src/main/java/com/wepong/pongdang/service/WalletService.java
Labels: 🐛 bug, 💻 edit, ✨ feature

#94 ✨🐛 [feat] 배포 후 기능 추가 및 서버 오류 수정
  src/main/java/com/wepong/pongdang/controller/GameRestController.java
  src/main/java/com/wepong/pongdang/controller/WalletController.java
  src/main/java/com/wepong/pongdang/model/multi/board/BoardGameService.java
  src/main/java/com/wepong/pongdang/model/multi/board/LandService.java
  src/main/java/com/wepong/pongdang/model/multi/turtle/TurtleGameService.java
  src/main/java/com/wepong/pongdang/service/BarcodeService.java
  src/main/java/com/wepong/pongdang/service/QuizCheckService.java
  src/main/java/com/wepong/pongdang/service/WalletService.java
  src/main/resources/application.yml
Labels: 🐛 bug
